#!/bin/bash -eux

FLAG_G="FALSE"

while getopts e:g OPT
do
  case $OPT in
    "e" ) ENV=$OPTARG ;;
    "g" ) FLAG_G="TRUE" ;;
      * ) echo "Usage: ./scripts/collect -e HopperBulletEnv-v0 [-g]" 1>&2
          exit 1 ;;
  esac
done

if [ "$FLAG_G" = "TRUE" ]; then
  GPU_OPTION="--gpu"
else
  GPU_OPTION=""
fi

# random collection
python -m d4rl_pybullet.collect --env $ENV --seed 0 $GPU_OPTION
python -m d4rl_pybullet.collect --env $ENV --seed 1 $GPU_OPTION
python -m d4rl_pybullet.collect --env $ENV --seed 2 $GPU_OPTION

# policy collection
python -m d4rl_pybullet.collect --env $ENV --load logs/${ENV}_0/final_model.pt $GPU_OPTION
python -m d4rl_pybullet.collect --env $ENV --load logs/${ENV}_1/final_model.pt $GPU_OPTION
python -m d4rl_pybullet.collect --env $ENV --load logs/${ENV}_2/final_model.pt $GPU_OPTION
