#!/bin/bash -eux

GPU_OPTION=""
N_SEEDS=3

while getopts e:gn: OPT
do
  case $OPT in
    "e" ) ENV=$OPTARG ;;
    "g" ) GPU_OPTION="--gpu" ;;
    "n" ) N_SEEDS=$OPTARG ;;
      * ) echo "Usage: ./scripts/collect -e HopperBulletEnv-v0 [-g] [-n 5]" 1>&2
          exit 1 ;;
  esac
done

for ((i=0; i < $N_SEEDS; i++)); do
  # random collection
  python -m d4rl_pybullet.collect --env $ENV --seed $i $GPU_OPTION

  # policy collection
  python -m d4rl_pybullet.collect --env $ENV
                                  --seed $i \
                                  --load logs/${ENV}_$i/final_model.pt \
                                  $GPU_OPTION
done
